import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ThreadSecuritySummary } from './types';

export const generateForensicPDF = (summary: ThreadSecuritySummary, participantCount: number) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Helper for colors
  const colors = {
    primary: [31, 41, 55], // Slate 800
    danger: [220, 38, 38], // Red 600
    warning: [217, 119, 6], // Amber 600
    success: [5, 150, 105], // Emerald 600
    muted: [107, 114, 128], // Gray 500
    light: [243, 244, 246], // Gray 100
  };

  const getRiskColor = (level: string) => {
    if (level === 'High') return colors.danger;
    if (level === 'Medium') return colors.warning;
    return colors.success;
  };

  // --- PAGE 1: COVER PAGE ---
  
  // Background Pattern / Border
  doc.setDrawColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.setLineWidth(1.5);
  doc.rect(5, 5, pageWidth - 10, pageHeight - 10);
  
  // Header Logo / Branding
  doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.rect(0, 30, pageWidth, 50, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INTELLIMAIL', 20, 55);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('CYBER INTELLIGENCE & FORENSICS DIVISION', 20, 65);
  
  // Classification
  doc.setFillColor(colors.danger[0], colors.danger[1], colors.danger[2]);
  doc.rect(pageWidth - 60, 45, 60, 10, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('CONFIDENTIAL', pageWidth - 30, 52, { align: 'center' });

  // Report Title
  doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text('SECURITY ANALYSIS', 20, 110);
  doc.text('FORENSIC REPORT', 20, 125);
  
  // Case Details
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 140, pageWidth - 20, 140);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('CASE IDENTIFIER:', 20, 155);
  doc.setFont('helvetica', 'normal');
  doc.text(summary.threadId, 70, 155);
  
  doc.setFont('helvetica', 'bold');
  doc.text('REPORT STATUS:', 20, 165);
  doc.setFont('helvetica', 'normal');
  doc.text('FINALIZED', 70, 165);
  
  doc.setFont('helvetica', 'bold');
  doc.text('ANALYSIS DATE:', 20, 175);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleString(), 70, 175);
  
  doc.setFont('helvetica', 'bold');
  doc.text('THREAT LEVEL:', 20, 185);
  const riskColor = getRiskColor(summary.overallRiskLevel);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.text(`${summary.overallRiskLevel.toUpperCase()} (${summary.overallRisk}/100)`, 70, 185);

  // Disclaimer
  doc.setTextColor(colors.muted[0], colors.muted[1], colors.muted[2]);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const disclaimer = 'This report is generated by the IntelliMail AI Neural Engine. The findings contained herein are based on behavioral analysis, LSTM model inferences, and link reputation services. This document is intended for authorized security personnel only.';
  doc.text(doc.splitTextToSize(disclaimer, pageWidth - 40), 20, pageHeight - 30);
  
  // Footer page number
  doc.setFont('helvetica', 'normal');
  doc.text('Page 1 of 2', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // --- PAGE 2: ANALYSIS DETAILS ---
  doc.addPage();
  
  // Border
  doc.setDrawColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.rect(5, 5, pageWidth - 10, pageHeight - 10);
  
  // Header
  doc.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.rect(5, 5, pageWidth - 10, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('EXECUTIVE FORENSIC SUMMARY - CASE: ' + summary.threadId.substring(0, 12), 15, 15);
  
  // Section 1: Executive Verdict
  doc.setTextColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1.0 EXECUTIVE VERDICT', 15, 35);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const verdictLines = doc.splitTextToSize(summary.threadThreatLevel, pageWidth - 30);
  doc.text(verdictLines, 15, 45);
  
  let nextY = 45 + (verdictLines.length * 5) + 10;
  
  // Section 2: Technical Indicators
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2.0 TECHNICAL INDICATORS', 15, nextY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Emails Analyzed: ${summary.emails.length}`, 15, nextY + 10);
  doc.text(`Unique Participants: ${participantCount}`, 15, nextY + 17);
  doc.text(`Primary Attack Vector: ${summary.attackType || 'N/A'}`, 15, nextY + 24);
  doc.text(`AI Confidence Label: ${summary.confidenceLabel || 'N/A'}`, 15, nextY + 31);
  
  nextY = nextY + 45;
  
  // Section 3: Detailed Evidence Log
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('3.0 DETAILED EVIDENCE LOG', 15, nextY);
  
  const tableData = summary.emails.map((email, index) => [
    index + 1,
    email.sender.length > 30 ? email.sender.substring(0, 27) + '...' : email.sender,
    { content: email.riskLevel, styles: { textColor: getRiskColor(email.riskLevel) } },
    email.riskScore,
    email.lstmConfidence?.toFixed(2) || 'N/A',
    new Date(email.timestamp).toLocaleDateString()
  ]);
  
  autoTable(doc, {
    startY: nextY + 5,
    margin: { left: 15, right: 15 },
    head: [['#', 'Sender', 'Risk', 'Score', 'LSTM', 'Date']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: colors.primary, textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 60 },
      2: { cellWidth: 25 },
      3: { cellWidth: 20 },
      4: { cellWidth: 20 },
      5: { cellWidth: 35 },
    }
  });
  
  // Section 4: Recommendations
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('4.0 REMEDIATION STRATEGY', 15, finalY);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const recommendations = [
    '• Verify sender identity via secondary out-of-band channel.',
    '• Do not interact with links or attachments from high-risk messages.',
    '• Review internal security protocols if multiple participants are involved.',
    '• Monitor for potential data exfiltration or session hijacking attempts.'
  ];
  
  recommendations.forEach((rec, i) => {
    doc.text(rec, 15, finalY + 10 + (i * 6));
  });
  
  // Signature Area
  doc.setDrawColor(colors.primary[0], colors.primary[1], colors.primary[2]);
  doc.line(140, pageHeight - 40, pageWidth - 15, pageHeight - 40);
  doc.setFontSize(8);
  doc.text('AUTHORIZED BY INTELLIMAIL AI', 140, pageHeight - 35);
  doc.text('DIGITAL SIGNATURE VERIFIED', 140, pageHeight - 31);
  
  doc.save(`IntelliMail_Forensic_Report_${summary.threadId.substring(0, 8)}.pdf`);
};
